export const products = [
    { id: "Item 1", name: "Item name 1", description: "Foo" },
    { id: "Item 2", name: "Item name 2", description: "Bar" },
    { id: "Item 3", name: "Item name 3", description: "Baz" },
    { id: "Item 4", name: "Item name 4", description: "Qux" },
    { id: "Item 5", name: "Item name 5", description: "Quux" },
    { id: "Item 6", name: "Item name 6", description: "Corge" },
    { id: "Item 7", name: "Item name 7", description: "Grault" },
    { id: "Item 8", name: "Item name 8", description: "Garply" },
    { id: "Item 9", name: "Item name 9", description: "Waldo" },
    { id: "Item 10", name: "Item name 10", description: "Fred" },
    { id: "Item 11", name: "Item name 11", description: "Plugh" },
    { id: "Item 12", name: "Item name 12", description: "Xyzzy" },
    { id: "Item 13", name: "Item name 13", description: "Thud" },
    { id: "Item 14", name: "Item name 14", description: "Lorem" },
];
